/**
 * Type Exports
 *
 * Central export point for all types
 */

// Database types
export * from './database.types';

// User types
export * from './user.types';

// Navigation types (will be auto-generated by Expo Router)
// export * from './navigation.types';

// API response types
export interface ApiResponse<T> {
  data: T | null;
  error: ApiError | null;
}

export interface ApiError {
  message: string;
  code?: string;
  details?: unknown;
}

export interface PaginatedResponse<T> {
  data: T[];
  total: number;
  page: number;
  limit: number;
  hasMore: boolean;
}

// Match types
export interface MatchWithUser {
  id: string;
  created_at: string;
  other_user: {
    id: string;
    first_name: string;
    display_name: string;
    primary_photo_url: string | null;
    is_online?: boolean;
    last_active?: string;
  };
  last_message?: {
    content: string;
    created_at: string;
    sender_id: string;
    is_read: boolean;
  };
  unread_count: number;
}

// Message types
export interface MessageWithSender {
  id: string;
  content: string | null;
  message_type: 'text' | 'image' | 'voice' | 'gif' | 'icebreaker';
  media_url: string | null;
  created_at: string;
  is_read: boolean;
  sender: {
    id: string;
    first_name: string;
    photo_url: string | null;
  };
  is_mine: boolean;
}

// Swipe result
export interface SwipeResult {
  success: boolean;
  isMatch: boolean;
  matchId?: string;
  matchedUser?: {
    id: string;
    first_name: string;
    primary_photo_url: string | null;
  };
}

// Discovery filters
export interface DiscoveryFilters {
  age_min: number;
  age_max: number;
  distance_max_miles: number;
  gender_preference: string[];
  jewish_backgrounds: string[];
  observance_levels: string[];
  partner_must_be_jewish: boolean | null;
  height_min_cm?: number;
  height_max_cm?: number;
  has_photos_verified?: boolean;
  safta_approved_only?: boolean;
  active_within_days?: number;
}

// Location types
export interface Location {
  latitude: number;
  longitude: number;
  city?: string;
  state?: string;
  country?: string;
}

// Notification types
export type NotificationType =
  | 'new_match'
  | 'new_message'
  | 'new_like'
  | 'super_like'
  | 'safta_like'
  | 'safta_connection'
  | 'profile_boost'
  | 'daily_picks';

export interface PushNotification {
  id: string;
  type: NotificationType;
  title: string;
  body: string;
  data?: Record<string, unknown>;
  created_at: string;
  read_at?: string;
}

// Premium types
export type PremiumFeature =
  | 'see_likes'
  | 'unlimited_swipes'
  | 'super_likes'
  | 'rewind'
  | 'boost'
  | 'advanced_filters'
  | 'read_receipts'
  | 'priority_likes'
  | 'message_before_match';

export type PremiumPlan = 'free' | 'mazal_gold' | 'mazal_platinum';

export interface PremiumEntitlements {
  isPremium: boolean;
  plan: PremiumPlan;
  features: PremiumFeature[];
  superLikesRemaining: number;
  boostsRemaining: number;
  expiresAt?: string;
}
